images:
  vsphereCloudControllerManager: "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.1.0"
  csiAttacher: "quay.io/k8scsi/csi-attacher:v3.0.0"
  csiDriver: "gcr.io/cloud-provider-vsphere/csi/release/driver:v2.1.0"
  livenessProbe: "quay.io/k8scsi/livenessprobe:v2.1.0"
  vsphereSyncer: "gcr.io/cloud-provider-vsphere/csi/release/syncer:v2.1.0"
  csiProvisioner: "quay.io/k8scsi/csi-provisioner:v2.0.0"
  csiResizer: "quay.io/k8scsi/csi-resizer:v1.0.0"
  nodeDriverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v2.0.1"

vcenter:
  # host: vcenter.example.com
  insecurehost: true
  # username: admin 
  # password: root
  # datacenter: DC1

kubelet:
  path: /var/lib/kubelet

storageclass:
  name: vsphere-csi
  default: true
  fstype: ext4
  # storagepolicyname: my-storage-policy
  # datastoreurl: ds:///vmfs/volumes/vsan:528c27f173c2088e-2126e911985dc3aa/
  # reclaimpolicy: Delete