apiVersion: v1
kind: Secret
metadata:
  name: cpi-global-secret
  namespace: kube-system
stringData:
  {{ .Values.vcenter.host }}.username: {{ .Values.vcenter.username | quote }}
  {{ .Values.vcenter.host }}.password: {{ .Values.vcenter.password | quote }}
