{{- if .Values.storageclass  }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 name: {{ .Values.storageclass.name }}
 annotations:
  storageclass.kubernetes.io/is-default-class: {{ .Values.storageclass.default | quote }}
provisioner: csi.vsphere.vmware.com
parameters:
 fstype: {{ .Values.storageclass.fstype }}
 {{- if .Values.storageclass.datastoreurl  }}
 DatastoreURL: {{ .Values.storageclass.datastoreurl | quote }}
 {{- end }}
 {{- if .Values.storageclass.storagepolicyname }}
 storagepolicyname: {{ .Values.storageclass.storagepolicyname | quote }}
 {{- end }}
{{- if .Values.storageclass.reclaimpolicy }}
reclaimPolicy: {{ .Values.storageclass.reclaimpolicy }}
{{- end }}
{{- end }}
