apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: kube-system
type: Opaque
stringData:
  csi-vsphere.conf: |-
    [Global]
    cluster-id = "cluster-{{ randAlpha 5 | lower }}"
  
    [VirtualCenter {{ .Values.vcenter.host | quote }}]
    insecure-flag = {{ .Values.vcenter.insecurehost | quote }}
    user = {{ .Values.vcenter.username | quote }}
    password = {{ .Values.vcenter.password | quote }}
    port = {{ .Values.vcenter.port | quote }}
    datacenters = {{ .Values.vcenter.datacenter | quote }}
